"""empty message

Revision ID: eb8c60644c27
Revises: 
Create Date: 2020-12-09 02:06:55.858520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8c60644c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('show_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time', sa.DATE(), nullable=True),
    sa.Column('place', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mail', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('is_avaliable', sa.String(length=20), nullable=True),
    sa.Column('clas', sa.String(length=20), nullable=True),
    sa.Column('show_', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_'], ['show.show_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('users')
    op.drop_table('show')
    # ### end Alembic commands ###
